#!/bin/bash

if [ $1 == "install" ]; then

	if [ $(dpkg-query -W -f='${Version}\n' "xbian-update") != "1.0-0.4" ]; then
		echo "!-------------------------------------------------!"
		echo "!                                                 !"
		echo "! Please install this update on XBian 1.0 Alpha 4 !"
		echo "!                                                 !"
		echo "!-------------------------------------------------!"
		exit 1;
	fi

fi

if [ $1 == "upgrade" ]; then

	if [ $(dpkg-query -W -f='${Version}\n' "xbian-update") != "1.0-0.5" -a $(dpkg-query -W -f='${Version}\n' "xbian-update") != "1.0-0.4" ]; then
		echo "!-------------------------------------------------!"
		echo "!                                                 !"
		echo "! Please install this update on XBian 1.0 Alpha 4 !"
		echo "!    or use it to reinstall XBian 1.0 Alpha 5     !"
		echo "!                                                 !"
		echo "!-------------------------------------------------!"
		exit 1;
	fi

fi

if [ $1 == "install" -o $1 == "upgrade" ]; then

	echo "1) Stopping XBMC";
	/etc/init.d/xbmc stop 1>/dev/null 2>/dev/null >/dev/null

	if [ ! -d "/boot" ]; then
		mkdir -p "/boot";
	fi

	if [ ! -d "/etc/init.d" ]; then
		mkdir -p "/etc/init.d";
	fi

	if [ ! -d "/lib/firmware" ]; then
		mkdir -p "/lib/firmware";
	fi

	if [ ! -d "/usr/bin" ]; then
		mkdir -p "/usr/bin";
	fi

	if [ ! -d "/usr/share/images/splash" ]; then
		mkdir -p "/usr/share/images/splash";
	fi

	if [ ! -d "/usr/share/fonts/splash" ]; then
		mkdir -p "/usr/share/fonts/splash";
	fi

	if [ ! -d "/usr/local/include/libcec" ]; then
		mkdir -p "/usr/local/include/libcec";
	fi

	if [ ! -d "/usr/local/lib/pkgconfig" ]; then
		mkdir -p "/usr/local/lib/pkgconfig";
	fi

	if [ ! -d "/usr/local/lib" ]; then
		mkdir -p "/usr/local/lib";
	fi

	if [ ! -d "/usr/local/bin" ]; then
		mkdir -p "/usr/local/bin";
	fi
	
	if [ -f "/boot/initramfs.gz" ]; then
		mv /boot/initramfs.gz /boot/initramfs.gz.xbian
	fi
	
	if [ -f "/boot/cmdline.txt" ]; then
		mv /boot/cmdline.txt /boot/cmdline.txt.xbian
	fi
	
	echo "2) Installing new files" 
fi
