#!/bin/bash

if [ $1 == "remove" ]; then

	if [ -f /boot/kernel3_8_11.img ]; then
		rm /boot/kernel3_8_11.img
	fi

	if [ -d /lib/modules/3.8.11+ ]; then
		rm -r /lib/modules/3.8.11+
	fi

fi

if [ $1 == "upgrade" ]; then

	if [ -f /boot/kernel3_8_11.img ]; then
		rm /boot/kernel3_8_11.img
	fi

fi
