#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

        /etc/init.d/xbmc stop 1>/dev/null 2>/dev/null >/dev/null

	if [ ! -d "/etc/init.d" ]; then
		mkdir -p "/etc/init.d";
	fi

	if [ ! -d "/usr/local/bin" ]; then
		mkdir -p "/usr/local/bin";
	fi

	if [ ! -d "/usr/local/lib" ]; then
		mkdir -p "/usr/local/lib";
	fi

fi
