#!/bin/bash

if [ $1 == "remove" ]; then

	update-rc.d xbmc-wiiremote remove

	if [ -f /etc/init.d/xbmc-wiiremote ]; then
		rm /etc/init.d/xbmc-wiiremote;
	fi

	if [ -d /usr/local/bin/xbmc-wiiremote ]; then
		rm -r /usr/local/bin/xbmc-wiiremote;
	fi

	if [ -d /usr/local/lib/libwiiuse.so ]; then
		rm -r /usr/local/lib/libwiiuse.so;
	fi

fi
