#!/bin/bash

if [ $1 == "configure" ]; then

	update-rc.d maraschino defaults &>/dev/null

	chmod 777 /usr/local/share/maraschino
	chmod 777 /usr/local/etc/maraschino
	
	/etc/init.d/maraschino start &>/dev/null

fi
