#!/bin/bash

if[ $1 == "install" -o $1 == "upgrade" ]; then

	if [ ! -d "/etc/init.d" ]; then
		mkdir -p "/etc/init.d";
	fi

	if [ ! -d "/usr/local/share/maraschino" ]; then
		mkdir -p "/usr/local/share/maraschino";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib" ]; then
		mkdir -p "/usr/local/share/maraschino/lib";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/utorrentclient" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/utorrentclient";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/feedparser" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/feedparser";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/frontend" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/frontend";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/frontend/templates" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/frontend/templates";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/admin" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/admin";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/admin/templates" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/admin/templates";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/admin/static" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/admin/static";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/admin/static/css" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/moduleapp/apps/admin/static/css";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/config_package_app" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/config_package_app";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/flaskext" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/flaskext";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/flaskext/oldext_package" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/flaskext/oldext_package";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/frontend" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/frontend";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/frontend/templates" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/frontend/templates";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/frontend/templates/frontend" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/frontend/templates/frontend";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin/templates" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin/templates";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin/templates/admin" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin/templates/admin";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin/static" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin/static";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin/static/css" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/blueprintapp/apps/admin/static/css";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/flask_broken" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/flask_broken";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/subdomaintestmodule" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/subdomaintestmodule";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/subdomaintestmodule/static" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/subdomaintestmodule/static";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/flask_newext_package" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/test_apps/flask_newext_package";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/templates" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/templates";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/templates/nested" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/templates/nested";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/testsuite/static" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/testsuite/static";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flask/ext" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flask/ext";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/pastebin" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/pastebin";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/wsgiserver" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/wsgiserver";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/weatherfeed" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/weatherfeed";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/jinja2" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/jinja2";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/jinja2/testsuite" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/jinja2/testsuite";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/jinja2/testsuite/res" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/jinja2/testsuite/res";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/jinja2/testsuite/res/templates" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/jinja2/testsuite/res/templates";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/jinja2/testsuite/res/templates/foo" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/jinja2/testsuite/res/templates/foo";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/jinja2/_markupsafe" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/jinja2/_markupsafe";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/apscheduler" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/apscheduler";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/apscheduler/jobstores" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/apscheduler/jobstores";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/apscheduler/triggers" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/apscheduler/triggers";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/apscheduler/triggers/cron" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/apscheduler/triggers/cron";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/flaskext" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/flaskext";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/contrib" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/contrib";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/testsuite" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/testsuite";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/testsuite/res" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/testsuite/res";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/testsuite/contrib" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/testsuite/contrib";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/webkit3-2png1txt" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/webkit3-2png1txt";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/opera8-2png1txt" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/opera8-2png1txt";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/ie6-2png1txt" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/ie6-2png1txt";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/firefox3-2png1txt" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/firefox3-2png1txt";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/firefox3-2pnglongtext" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/testsuite/multipart/firefox3-2pnglongtext";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/debug" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/debug";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/werkzeug/debug/shared" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/werkzeug/debug/shared";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/ext" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/ext";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/drizzle" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/drizzle";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/mssql" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/mssql";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/oracle" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/oracle";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/postgresql" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/postgresql";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/access" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/access";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/firebird" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/firebird";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/mysql" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/mysql";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/sybase" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/sybase";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/informix" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/informix";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/maxdb" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/maxdb";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/dialects/sqlite" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/dialects/sqlite";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/databases" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/databases";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/sql" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/sql";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/engine" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/engine";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/util" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/util";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/orm" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/orm";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/sqlalchemy/connectors" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/sqlalchemy/connectors";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/xbmc" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/xbmc";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/transmissionrpc" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/transmissionrpc";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/xmltodict" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/xmltodict";
	fi


	if [ ! -d "/usr/local/share/maraschino/lib/jsonrpclib" ]; then
		mkdir -p "/usr/local/share/maraschino/lib/jsonrpclib";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates" ]; then
		mkdir -p "/usr/local/share/maraschino/templates";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/library" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/library";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/recently_added" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/recently_added";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/mobile" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/mobile";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/mobile/sickbeard" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/mobile/sickbeard";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/mobile/couchpotato" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/mobile/couchpotato";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/mobile/headphones" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/mobile/headphones";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/mobile/xbmc" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/mobile/xbmc";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/mobile/sabnzbd" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/mobile/sabnzbd";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/mobile/trakt" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/mobile/trakt";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/sickbeard" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/sickbeard";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/couchpotato" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/couchpotato";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/traktplus" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/traktplus";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/nzbget" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/nzbget";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/headphones" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/headphones";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/includes" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/includes";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/sabnzbd" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/sabnzbd";
	fi


	if [ ! -d "/usr/local/share/maraschino/templates/dialogs" ]; then
		mkdir -p "/usr/local/share/maraschino/templates/dialogs";
	fi


	if [ ! -d "/usr/local/share/maraschino/scripts" ]; then
		mkdir -p "/usr/local/share/maraschino/scripts";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git" ]; then
		mkdir -p "/usr/local/share/maraschino/.git";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/logs" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/logs";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/logs/refs" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/logs/refs";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/logs/refs/remotes" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/logs/refs/remotes";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/logs/refs/remotes/origin" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/logs/refs/remotes/origin";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/logs/refs/heads" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/logs/refs/heads";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/hooks" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/hooks";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/info" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/info";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/refs" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/refs";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/refs/remotes" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/refs/remotes";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/refs/remotes/origin" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/refs/remotes/origin";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/refs/heads" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/refs/heads";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/refs/tags" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/refs/tags";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/branches" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/branches";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/objects" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/objects";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/objects/pack" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/objects/pack";
	fi


	if [ ! -d "/usr/local/share/maraschino/.git/objects/info" ]; then
		mkdir -p "/usr/local/share/maraschino/.git/objects/info";
	fi


	if [ ! -d "/usr/local/share/maraschino/modules" ]; then
		mkdir -p "/usr/local/share/maraschino/modules";
	fi


	if [ ! -d "/usr/local/share/maraschino/maraschino" ]; then
		mkdir -p "/usr/local/share/maraschino/maraschino";
	fi


	if [ ! -d "/usr/local/share/maraschino/static" ]; then
		mkdir -p "/usr/local/share/maraschino/static";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/mobile" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/mobile";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/player_buttons" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/player_buttons";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/star_ratings" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/star_ratings";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/placeholder" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/placeholder";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/weather" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/weather";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/backgrounds" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/backgrounds";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/applications" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/applications";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/trakt" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/trakt";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/notifications" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/notifications";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/images/alpha" ]; then
		mkdir -p "/usr/local/share/maraschino/static/images/alpha";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/js" ]; then
		mkdir -p "/usr/local/share/maraschino/static/js";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/js/lib" ]; then
		mkdir -p "/usr/local/share/maraschino/static/js/lib";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/js/mobile" ]; then
		mkdir -p "/usr/local/share/maraschino/static/js/mobile";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/less" ]; then
		mkdir -p "/usr/local/share/maraschino/static/less";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/less/mobile" ]; then
		mkdir -p "/usr/local/share/maraschino/static/less/mobile";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/less/mobile/lib" ]; then
		mkdir -p "/usr/local/share/maraschino/static/less/mobile/lib";
	fi


	if [ ! -d "/usr/local/share/maraschino/static/less/mobile/lib/images" ]; then
		mkdir -p "/usr/local/share/maraschino/static/less/mobile/lib/images";
	fi

	if [ ! -d "/etc/default" ]; then
		mkdir -p "/etc/default";
	fi
fi
